<?php

function bankstat_menu() {
    $items = array();

    $items['bankstat/import'] = array( 
        'title' => 'Import page', 
        'description' => 'The page to import your bank data',
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('bankstat_import_form'),
        'access callback' => TRUE,
        'file' => 'bankstat.forms.inc',
    );

    $items['bankstat/assign/manually'] = array( 
        'title' => 'Assign nodes', 
        'description' => 'The page to assign tags to your bank data',
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('bankstat_assign_all_form'),
        'access callback' => TRUE,
        'file' => 'bankstat.forms.inc',
    );

    $items['bankstat/assign/automatically'] = array( 
        'title' => 'Assign nodes automatically', 
        'description' => 'The page to automatically assign tags to your bank data',
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('bankstat_assign_all_automatically_form'),
        'access callback' => TRUE,
        'file' => 'bankstat.forms.inc',
    );

    $items['bankstat/view/combined'] = array( 
        'title' => 'Statistics combined charts', 
        'description' => 'Page to view statistics bank data',
        'page callback' => 'drupal_get_form', 
        'page arguments' => array('bankstat_statistics_combined'),
        'access callback' => TRUE,
        'file' => 'bankstat.forms.inc',
    );

    return $items;
}

