<?php

function bankstat_menu() {
	$items = array();

	$items['bankstat/import'] = array( 
		'title' => 'Import page', 
		'description' => 'The page to import your bank data',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('bankstat_import_form'),
		'access callback' => TRUE,
		'file' => 'bankstat.forms.inc',
	);

	$items['bankstat/view/all'] = array( 
		'title' => 'View all nodes', 
		'description' => 'The page to view all your bank data',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('bankstat_view_all_form'),
		'access callback' => TRUE,
		'file' => 'bankstat.forms.inc',
	);

	$items['bankstat/view/expensetag'] = array( 
		'title' => 'View expense tag nodes', 
		'description' => 'The page to view all your bank data with a specific tag',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('bankstat_view_node_expensetype_form'),
		'access callback' => TRUE,
		'file' => 'bankstat.forms.inc',
	);

	$items['bankstat/view/stats'] = array( 
		'title' => 'Statistics', 
		'description' => 'Page to view statistics bank data',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('bankstat_statistics'),
		'access callback' => TRUE,
		'file' => 'bankstat.forms.inc',
	);

	$items['bankstat/view/linechart'] = array( 
		'title' => 'Statistics line chart', 
		'description' => 'Page to view statistics bank data',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('bankstat_statistics_linechart'),
		'access callback' => TRUE,
		'file' => 'bankstat.forms.inc',
	);

	return $items;
}

